INSERT INTO inventory_items (id, product, product_external_id, quantity_available, delete_at, update_at, created_at) VALUES
(gen_random_uuid(), 'Prego 18x27', gen_random_uuid(), 120, NULL, NOW(), NOW()),
(gen_random_uuid(), 'T�bua de Cedro', gen_random_uuid(), 45, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Martelo A�o Forjado', gen_random_uuid(), 30, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Serrote Profissional', gen_random_uuid(), 12, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Parafuso 3mm x 50mm', gen_random_uuid(), 800, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Cimento CP-II 50kg', gen_random_uuid(), 65, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Areia Fina', gen_random_uuid(), 200, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Brita 1', gen_random_uuid(), 180, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Tinta Acr�lica Branca', gen_random_uuid(), 75, NULL, NOW(), NOW()),
(gen_random_uuid(), 'L�mpada LED 9W', gen_random_uuid(), 140, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Chave de Fenda', gen_random_uuid(), 60, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Chave Philips', gen_random_uuid(), 55, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Trena 5m', gen_random_uuid(), 20, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Broca A�o R�pido 10mm', gen_random_uuid(), 35, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Arame Galvanizado 1kg', gen_random_uuid(), 90, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Esp�tula Inox 10cm', gen_random_uuid(), 25, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Rolo de Pintura 23cm', gen_random_uuid(), 48, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Tinta Spray Preto Fosco', gen_random_uuid(), 32, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Cano PVC 40mm', gen_random_uuid(), 100, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Joelho PVC 40mm', gen_random_uuid(), 95, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Registro Esfera 1"', gen_random_uuid(), 15, NULL, NOW(), NOW()),
(gen_random_uuid(), 'V�lvula de Reten��o', gen_random_uuid(), 10, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Bucha 8mm', gen_random_uuid(), 500, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Furadeira Impacto 650W', gen_random_uuid(), 8, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Lixadeira Orbital', gen_random_uuid(), 5, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Madeira Pinus 2x4', gen_random_uuid(), 160, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Chapa MDF 15mm', gen_random_uuid(), 40, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Espuma Expansiva', gen_random_uuid(), 22, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Selante PU Constru��o', gen_random_uuid(), 30, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Carrinho de M�o', gen_random_uuid(), 6, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Luvas de Raspa', gen_random_uuid(), 70, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Capacete de Seguran�a', gen_random_uuid(), 25, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Cinta de Eleva��o', gen_random_uuid(), 10, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Polia de A�o', gen_random_uuid(), 14, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Chave Inglesa 12"', gen_random_uuid(), 18, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Fita Veda Rosca', gen_random_uuid(), 250, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Resina Ep�xi 1L', gen_random_uuid(), 20, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Piso Cer�mico 60x60', gen_random_uuid(), 55, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Azulejo 30x30', gen_random_uuid(), 72, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Nivelador de Piso', gen_random_uuid(), 80, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Argamassa ACII', gen_random_uuid(), 67, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Rejunte Branco', gen_random_uuid(), 90, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Chave Allen Kit', gen_random_uuid(), 45, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Sarrafo de Madeira 3x1', gen_random_uuid(), 150, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Cadeado 40mm', gen_random_uuid(), 38, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Corrente Galvanizada 1m', gen_random_uuid(), 60, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Rodelo para Piso', gen_random_uuid(), 22, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Esp�tula de Borracha', gen_random_uuid(), 33, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Suporte de TV Articulado', gen_random_uuid(), 19, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Mangueira 1/2" 20m', gen_random_uuid(), 26, NULL, NOW(), NOW());
